### ISSUE TITLE
Robot moves to wrong cartesian rotation angles

### ISSUE THREAD

**Issue by MassaRoddel** [frankaemika/libfranka#27]
Since the introduction of rate limiter and lowpass filter the robot often moves to wrong cartesian rotation angles (about 50% chance). It works again if rate limiter and lowpass filter are disabled and setFilters() gets used.
The wrong angles seem to be always the same for the same destination angles.
The x,y,z coordinates are always correct.

**Comment by Tomakko** [comment]
I can verify the issue. 
MasseRoddel, can you tell me how to get it working? 
I am doing `robot.control(cartesian_pose_control_callback,franka::ControllerMode::kJointImpedance, false, 1000.0);`
and
`robot.setFilters(1000,1000,1000,1000,1000);`
but the issue is still the same.

**Comment by MassaRoddel** [comment]
I (have to) use robot.setFilters(5, 5, 5, 5, 5) to avoid acceleration/velocity discontinuity errors.

My ping test results are like:

60000 packets transmitted, 60000 received, 0% packet loss, time 60048ms
rtt min/avg/max/mdev = 0.144/0.217/0.365/0.010 ms

but still the success rate goes to low values.

Control command success rate of 9944 samples: 
Max: 1.00
Avg: 0.96
Min: 0.76

**Comment by MassaRoddel** [comment]
Does that mean that executing the control loop in a thread different from main thread makes it worse?

**Comment by tf-janr** [comment]
No, in this case we just included a library into the main.

**Comment by Tomakko** [comment]
Thanks, @MassaRoddel, setting your filter coefficients seems to fixed it indeed.

**Comment by Tomakko** [comment]
@tf-janr , how does the differences in reliability look like? You experience more of the errors your described when placing the cartesian pose callback function inside main?

**Comment by tf-janr** [comment]
It works more reliable direct in main. If you build the loop in separate class and include this library to main the rotation error occurs more often. 
The calculation of rotation works fine because O_T_EE_c is always correct. But when we get the orientation error the O_T_EE_d shows unexpected behavior.

**Comment by tf-janr** [comment]
We got exactly the same answer

**Comment by fwalch** [comment]
We finally have a system update available which should fix this issue. You can download it [here](https://s3.eu-central-1.amazonaws.com/franka-updates/update-2.1.3.img). This is compatible with libfranka 0.5.0.

**Comment by MassaRoddel** [comment]
Seems not to be fixed but it happens less often now.

**Comment by pantor** [comment]
I can confirm that the system update does not fix our orientation problems.

**Comment by fwalch** [comment]
Thanks for the feedback. We also received reports of this through support and are investigating.

**Comment by MassaRoddel** [comment]
Is this problem fixed by now or is there a workaround?

**Comment by fwalch** [comment]
With system update 2.1.4, this should be fixed. You can download it on https://frankaemika.github.io/
Let me know if you are still experiencing issues.

**Comment by sgabl** [comment]
I'm closing this issue. If the problem still persists, please contact support.
